//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CiaoApp.Web.Resources.Texts {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Actions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Actions() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CiaoApp.Web.Resources.Texts.Actions", typeof(Actions).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Accept.
        /// </summary>
        public static string AcceptAction {
            get {
                return ResourceManager.GetString("AcceptAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Allow.
        /// </summary>
        public static string AllowAction {
            get {
                return ResourceManager.GetString("AllowAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Decline.
        /// </summary>
        public static string DeclineAction {
            get {
                return ResourceManager.GetString("DeclineAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Promise.
        /// </summary>
        public static string PromiseAction {
            get {
                return ResourceManager.GetString("PromiseAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Quit.
        /// </summary>
        public static string QuitAction {
            get {
                return ResourceManager.GetString("QuitAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Refuse.
        /// </summary>
        public static string RefuseAction {
            get {
                return ResourceManager.GetString("RefuseAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Reject.
        /// </summary>
        public static string RejectAction {
            get {
                return ResourceManager.GetString("RejectAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Request.
        /// </summary>
        public static string RequestAction {
            get {
                return ResourceManager.GetString("RequestAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Revoke Acceptance.
        /// </summary>
        public static string RevokeAcceptAction {
            get {
                return ResourceManager.GetString("RevokeAcceptAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Revoke Promise.
        /// </summary>
        public static string RevokePromiseAction {
            get {
                return ResourceManager.GetString("RevokePromiseAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Revoke Request.
        /// </summary>
        public static string RevokeRequestAction {
            get {
                return ResourceManager.GetString("RevokeRequestAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Revoke Completion.
        /// </summary>
        public static string RevokeStateAction {
            get {
                return ResourceManager.GetString("RevokeStateAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Completed.
        /// </summary>
        public static string StateAction {
            get {
                return ResourceManager.GetString("StateAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to End.
        /// </summary>
        public static string StopAction {
            get {
                return ResourceManager.GetString("StopAction", resourceCulture);
            }
        }
    }
}
