//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CiaoApp.Web.Resources.Texts {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class States {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal States() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CiaoApp.Web.Resources.Texts.States", typeof(States).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Accepted.
        /// </summary>
        public static string Accepted {
            get {
                return ResourceManager.GetString("Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Accept revoked.
        /// </summary>
        public static string AcceptRevoked {
            get {
                return ResourceManager.GetString("AcceptRevoked", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Declined.
        /// </summary>
        public static string Declined {
            get {
                return ResourceManager.GetString("Declined", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Not ready.
        /// </summary>
        public static string NotReady {
            get {
                return ResourceManager.GetString("NotReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Promised.
        /// </summary>
        public static string Promised {
            get {
                return ResourceManager.GetString("Promised", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Promise revoked.
        /// </summary>
        public static string PromiseRevoked {
            get {
                return ResourceManager.GetString("PromiseRevoked", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Quit.
        /// </summary>
        public static string Quit {
            get {
                return ResourceManager.GetString("Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Rejected.
        /// </summary>
        public static string Rejected {
            get {
                return ResourceManager.GetString("Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Requested.
        /// </summary>
        public static string Requested {
            get {
                return ResourceManager.GetString("Requested", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Request revoked.
        /// </summary>
        public static string RequestRevoked {
            get {
                return ResourceManager.GetString("RequestRevoked", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Stated.
        /// </summary>
        public static string Stated {
            get {
                return ResourceManager.GetString("Stated", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to State revoked.
        /// </summary>
        public static string StateRevoked {
            get {
                return ResourceManager.GetString("StateRevoked", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Stopped.
        /// </summary>
        public static string Stopped {
            get {
                return ResourceManager.GetString("Stopped", resourceCulture);
            }
        }
    }
}
